from enum import Enum

class AuditAction(str, Enum):
    USER_REGISTERED = "USER_REGISTERED"
    USER_DELETED = "USER_DELETED"
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGOUT = "LOGOUT"
    
    TEAM_CREATED = "TEAM_CREATED"
    TEAM_DELETED = "TEAM_DELETED"
    TEAM_UPDATED = "TEAM_UPDATED"
    
    MEMBER_ADDED = "MEMBER_ADDED"
    MEMBER_REMOVED = "MEMBER_REMOVED"
    MEMBER_ROLE_CHANGED = "MEMBER_ROLE_CHANGED"

    TASK_CREATED = "TASK_CREATED"
    TASK_UPDATED = "TASK_UPDATED"
    TASK_DELETED = "TASK_DELETED"
    TASK_COMPLETED = "TASK_COMPLETED"